# From-scratch LLM inference engine for Apple Silicon.
# Build: make          (release)
#        make debug    (asserts, -O0, address sanitizer)
CXX      := clang++
CXXFLAGS := -std=c++20 -O3 -Wall -Wextra -Wno-unused-parameter -Isrc -MMD -MP
LDFLAGS  := -framework Metal -framework Foundation
SRCS_CPP := $(wildcard src/*.cpp)
SRCS_MM  := $(wildcard src/*.mm)
OBJS     := $(SRCS_CPP:src/%.cpp=build/%.o) $(SRCS_MM:src/%.mm=build/%.o)

all: llm

llm: $(OBJS)
	$(CXX) $(OBJS) -o $@ $(LDFLAGS)

build/%.o: src/%.cpp | build
	$(CXX) $(CXXFLAGS) -c $< -o $@

build/%.o: src/%.mm | build
	$(CXX) $(CXXFLAGS) -fobjc-arc -c $< -o $@

build:
	mkdir -p build

# Header dependencies generated by -MMD, so a header change rebuilds every object that includes it.
-include $(OBJS:.o=.d)

debug: CXXFLAGS := -std=c++20 -O0 -g -fsanitize=address -Wall -Wextra -Wno-unused-parameter -Isrc -MMD -MP
debug: LDFLAGS  += -fsanitize=address
debug: clean llm

clean:
	rm -rf build llm

.PHONY: all debug clean
