#!/usr/bin/env python3
"""Generates src/unicode_data.cpp: codepoint range tables for the categories the
Llama 3 pre-tokenizer regex needs: \\p{L} (letters), \\p{N} (numbers), \\s (whitespace)."""
import unicodedata, sys

def ranges(pred):
    out, start = [], None
    for cp in range(0x110000):
        hit = pred(cp)
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, cp - 1)); start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out

def cat(cp):
    try: return unicodedata.category(chr(cp))
    except ValueError: return "Cn"

tables = {
    "kLetterRanges": ranges(lambda cp: cat(cp)[0] == "L"),
    "kNumberRanges": ranges(lambda cp: cat(cp)[0] == "N"),
    "kWhitespaceRanges": ranges(lambda cp: chr(cp).isspace()),
}
out = ["// GENERATED by tests/gen_unicode.py from Python's unicodedata (Unicode %s). Do not edit." % unicodedata.unidata_version,
       "#include \"unicode.h\"", "", "namespace unicode {", ""]
for name, rs in tables.items():
    out.append("const Range %s[] = {" % name)
    for i in range(0, len(rs), 6):
        out.append("    " + " ".join("{0x%X, 0x%X}," % r for r in rs[i:i+6]))
    out.append("};")
    out.append("const size_t %sCount = %d;" % (name, len(rs)))
    out.append("")
out.append("}  // namespace unicode")
open(sys.argv[1], "w").write("\n".join(out) + "\n")
print({k: len(v) for k, v in tables.items()})
